import assets from "../assets/assets";
import type { Product } from "../types/product";
import womenProducts from "./womenProducts";

const products: Product[] = [
  {
    id: 1,
    name: "Cavalier Chelsea Boot",
    category: "Modern Boots",
    collection: "Heritage Collection",
    price: 380,
    image: assets.Cross,
    badge: "NEW SEASON",
    color: "Black",
    material: "Full Grain Leather",
    sizes: [40, 41, 42, 43],
  },
  {
    id: 2,
    name: "Mono Court Sneaker",
    category: "Minimalist Sneakers",
    collection: "Essential Line",
    price: 245,
    image: assets.Cross2,
    badge: "",
    color: "White",
    material: "Recycled Canvas",
    sizes: [39, 40, 41, 42],
  },
  {
    id: 3,
    name: "Savoy Penny Loafer",
    category: "Heritage Loafers",
    collection: "Craftsman Series",
    price: 320,
    image: assets.Cross3,
    badge: "LIMITED EDITION",
    color: "Brown",
    material: "Suede",
    sizes: [40, 41, 42, 43],
  },
  {
    id: 4,
    name: "Amalfi Strap Sandal",
    category: "Resort Sandals",
    collection: "Resort Wear",
    price: 195,
    image: assets.Cross4,
    color: "Beige",
    material: "Full Grain Leather",
    sizes: [39, 40, 41],
  },
  {
    id: 5,
    name: "Titan Derby Shoe",
    category: "Modern Boots",
    collection: "Modern Formal",
    price: 420,
    image: assets.Cross,
    color: "Black",
    material: "Full Grain Leather",
    sizes: [41, 42, 43, 44],
  },
  {
    id: 6,
    name: "Terra Canvas Trainer",
    category: "Minimalist Sneakers",
    collection: "Sustainable Choice",
    price: 185,
    image: assets.Cross2,
    color: "Grey",
    material: "Recycled Canvas",
    sizes: [39, 40, 41, 42],
  },
  //   {
  //     id: 7,
  //     name: "Oxford Heritage",
  //     category: "Heritage Loafers",
  //     collection: "Classic",
  //     price: 315,
  //     image: assets.Cross3,
  //     color: "Brown",
  //     material: "Suede",
  //     sizes: [40, 41, 42],
  //   },
  //   {
  //     id: 8,
  //     name: "Urban Runner",
  //     category: "Minimalist Sneakers",
  //     collection: "Daily",
  //     price: 210,
  //     image: assets.Cross4,
  //     color: "White",
  //     material: "Recycled Canvas",
  //     sizes: [39, 40, 41, 42],
  //   },
  ...womenProducts,
];

export default products;
