import assets from "./assets";
import type { Product } from "../types/product";

const womenProducts: Product[] = [
  {
    id: 101,
    name: "Ava Black Heel",
    category: "Women",
    price: 45000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 102,
    name: "Luna Leather Sandal",
    category: "Women",
    price: 38000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Brown",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 103,
    name: "Nova Court Sneaker",
    category: "Women",
    price: 52000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "White",
    material: "Canvas",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 104,
    name: "Highline Leather Boot",
    category: "Women",
    price: 65000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 105,
    name: "Ava Black Heel",
    category: "Women",
    price: 45000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 106,
    name: "Luna Leather Sandal",
    category: "Women",
    price: 38000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Brown",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 107,
    name: "Nova Court Sneaker",
    category: "Women",
    price: 52000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "White",
    material: "Canvas",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 108,
    name: "Highline Leather Boot",
    category: "Women",
    price: 65000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 109,
    name: "Sienna Classic Heel",
    category: "Women",
    price: 48000,
    image: assets.womanFoot1,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 110,
    name: "Amara Strappy Sandal",
    category: "Women",
    price: 42000,
    image: assets.womanFoot2,
    collection: "Women's Collection",
    color: "Brown",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 111,
    name: "Luna White Sneaker",
    category: "Women",
    price: 55000,
    image: assets.womanFoot3,
    collection: "Women's Collection",
    color: "White",
    material: "Canvas",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 112,
    name: "Monaco Leather Boot",
    category: "Women",
    price: 70000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 113,
    name: "Sienna Classic Heel",
    category: "Women",
    price: 48000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 114,
    name: "Amara Strappy Sandal",
    category: "Women",
    price: 42000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Brown",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 115,
    name: "Luna White Sneaker",
    category: "Women",
    price: 55000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "White",
    material: "Canvas",
    sizes: [38, 39, 40, 41],
  },
  {
    id: 116,
    name: "Monaco Leather Boot",
    category: "Women",
    price: 70000,
    image: assets.womanFoot4,
    collection: "Women's Collection",
    color: "Black",
    material: "Leather",
    sizes: [38, 39, 40, 41],
  },
];

export default womenProducts;
